# Alacritty configuration
# OS-specific settings are imported from os-specific.toml
# (install.sh creates this as a symlink to the right os-*.toml file)
general.import = ["~/.config/alacritty/os-specific.toml"]

[window]
title = "Alacritty"
dynamic_title = true
opacity = 0.93
blur = true

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"
