# Alacritty base configuration
# This file contains shared settings across all platforms
# OS-specific files (os-*.toml) import this file

[window]
title = "Alacritty"
dynamic_title = true
opacity = 0.93
blur = true

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

# Key bindings
[[keyboard.bindings]]
key = "N"
mods = "Control"
action = "SpawnNewInstance"
