# Alacritty configuration for Windows + WSL

[general]
working_directory = "C:/Users/james"

[window]
title = "Alacritty"
dynamic_title = true
opacity = 0.93
blur = true

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

# Key bindings
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

# --- WORD JUMPS ---
# Ctrl+Left / Ctrl+Right → move by word
[[keyboard.bindings]]
key = "Left"
mods = "Control"
chars = "\u001b[1;5D"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
chars = "\u001b[1;5C"

# --- WORD DELETE ---
# Ctrl+Backspace → delete previous word
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

# Ctrl+Delete → delete next word
[[keyboard.bindings]]
key = "Delete"
mods = "Control"
chars = "\u0005"

[terminal.shell]
program = "wsl.exe"
args = ["--distribution", "Ubuntu", "--exec", "zsh", "-l"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

# Catppuccin Mocha theme - vibrant colors
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"
