
# DISABLED: Powerlevel10k instant prompt (testing nvim paste issue)
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#   source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi


# If you come from bash you might have to change your $PATH.

export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

########## PATH (early) ##########
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Put Homebrew on PATH early (works in Alacritty/login shells)
if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"   # Apple Silicon
elif [ -x /usr/local/bin/brew ]; then
  eval "$(/usr/local/bin/brew shellenv)"      # Intel

fi




# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
ZSH_THEME="agnoster"


# Set list of themes to pick from when loading at random

# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"


# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13


# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"


# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"


# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:

# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.

# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)

# Add wisely, as too many plugins slow down shell startup.
plugins=(
git z fzf history-substring-search sudo colored-man-pages

  zsh-autosuggestions zsh-syntax-highlighting

)


source $ZSH/oh-my-zsh.sh

export GIT_PAGER=cat



export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Ensure a default Node is selected so ~/.nvm/.../bin is added to PATH immediately
if command -v nvm >/dev/null 2>&1; then
  nvm alias default &>/dev/null || nvm alias default node
  nvm use --silent default >/dev/null 2>&1
fi

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"


# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# Fix tmux color issues

if [[ -n "$TMUX" ]]; then
    export TERM=tmux-256color
fi

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh

# - $ZSH_CUSTOM/macos.zsh

# For a full list of active aliases, run alias.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias dtf='cd ~/dotfiles && nvim .'

# Obsidian CLI aliases
alias obc='obsidian-cli'
alias obc-search='obsidian-cli search | xargs -I {} nvim ~/obsidian-2025/{}'
alias obc-daily='nvim ~/obsidian-2025/$(date +%Y-%m-%d).md'
alias obc-new='nvim ~/obsidian-2025/$(date +%Y%m%d%H%M).md'
alias obc-open='obsidian-cli open'

#### Google Cloud SDK ####
[ -f "$HOME/Downloads/google-cloud-sdk/path.zsh.inc" ] && \
  . "$HOME/Downloads/google-cloud-sdk/path.zsh.inc"
[ -f "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc" ] && \
  . "$HOME/Downloads/google-cloud-sdk/completion.zsh.inc"

export PATH="$HOME/.local/bin:$PATH"

prompt_context() { }

# OS-specific configuration
if [[ "$(uname -s)" == "Darwin" ]]; then
  # macOS-specific config
  [ -f "$HOME/dotfiles/configs/zsh/zshrc-mac" ] && source "$HOME/dotfiles/configs/zsh/zshrc-mac"
elif [[ "$(uname -s)" == "Linux" ]] && grep -qi microsoft /proc/version 2>/dev/null; then
  # WSL-specific config
  [ -f "$HOME/dotfiles/configs/zsh/zshrc-wsl" ] && source "$HOME/dotfiles/configs/zsh/zshrc-wsl"
elif [[ "$(uname -s)" == "Linux" ]]; then
  # Linux-specific config
  [ -f "$HOME/dotfiles/configs/zsh/zshrc-linux" ] && source "$HOME/dotfiles/configs/zsh/zshrc-linux"
fi

source "$HOME/dotfiles/configs/zsh/zshrc_conf/constants.zsh"
source "$HOME/dotfiles/configs/zsh/zshrc_conf/cr.zsh"

# Tmux sessionizer - Control-f to fuzzy find and switch sessions
bindkey -s ^f "tmux-sessionizer\n"

# Persistent tmux sessions - Alt-7,8,9,0
bindkey -s '\e7' "tmux-session-persistent dotfiles\n"
bindkey -s '\e8' "tmux-session-persistent gweb-diamond-valley\n"
bindkey -s '\e9' "tmux-session-persistent placeholder-9\n"
bindkey -s '\e0' "tmux-session-persistent placeholder-0\n"
